/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterUserRouteImport } from './routes/register-user'
import { Route as RegisterExpertRouteImport } from './routes/register-expert'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as IndexRouteImport } from './routes/index'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterUserRoute = RegisterUserRouteImport.update({
  id: '/register-user',
  path: '/register-user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterExpertRoute = RegisterExpertRouteImport.update({
  id: '/register-expert',
  path: '/register-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expert': typeof ExpertRoute
  '/login': typeof LoginRoute
  '/register-expert': typeof RegisterExpertRoute
  '/register-user': typeof RegisterUserRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user': typeof UserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expert': typeof ExpertRoute
  '/login': typeof LoginRoute
  '/register-expert': typeof RegisterExpertRoute
  '/register-user': typeof RegisterUserRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user': typeof UserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expert': typeof ExpertRoute
  '/login': typeof LoginRoute
  '/register-expert': typeof RegisterExpertRoute
  '/register-user': typeof RegisterUserRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user': typeof UserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expert'
    | '/login'
    | '/register-expert'
    | '/register-user'
    | '/sitemap.xml'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expert'
    | '/login'
    | '/register-expert'
    | '/register-user'
    | '/sitemap.xml'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/expert'
    | '/login'
    | '/register-expert'
    | '/register-user'
    | '/sitemap.xml'
    | '/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpertRoute: typeof ExpertRoute
  LoginRoute: typeof LoginRoute
  RegisterExpertRoute: typeof RegisterExpertRoute
  RegisterUserRoute: typeof RegisterUserRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-user': {
      id: '/register-user'
      path: '/register-user'
      fullPath: '/register-user'
      preLoaderRoute: typeof RegisterUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-expert': {
      id: '/register-expert'
      path: '/register-expert'
      fullPath: '/register-expert'
      preLoaderRoute: typeof RegisterExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpertRoute: ExpertRoute,
  LoginRoute: LoginRoute,
  RegisterExpertRoute: RegisterExpertRoute,
  RegisterUserRoute: RegisterUserRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
